// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BytesMessage.proto

package com.lkf.remotecontrol.models;

public final class BytesMessageProto {
  private BytesMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code remotecontrol.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>VIDEO_STREAM = 0;</code>
     */
    VIDEO_STREAM(0),
    /**
     * <code>TOUCH_INPUT = 1;</code>
     */
    TOUCH_INPUT(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>VIDEO_STREAM = 0;</code>
     */
    public static final int VIDEO_STREAM_VALUE = 0;
    /**
     * <code>TOUCH_INPUT = 1;</code>
     */
    public static final int TOUCH_INPUT_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return VIDEO_STREAM;
        case 1: return TOUCH_INPUT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return BytesMessageProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:remotecontrol.Type)
  }

  public interface BytesMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:remotecontrol.BytesMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.remotecontrol.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.remotecontrol.Type type = 1;</code>
     * @return The type.
     */
    Type getType();

    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code remotecontrol.BytesMessage}
   */
  public static final class BytesMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:remotecontrol.BytesMessage)
      BytesMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BytesMessage.newBuilder() to construct.
    private BytesMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BytesMessage() {
      type_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new BytesMessage();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BytesMessageProto.internal_static_remotecontrol_BytesMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BytesMessageProto.internal_static_remotecontrol_BytesMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BytesMessage.class, Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_ = 0;
    /**
     * <code>.remotecontrol.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.remotecontrol.Type type = 1;</code>
     * @return The type.
     */
    @Override public Type getType() {
      Type result = Type.forNumber(type_);
      return result == null ? Type.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    @Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != Type.VIDEO_STREAM.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != Type.VIDEO_STREAM.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BytesMessage)) {
        return super.equals(obj);
      }
      BytesMessage other = (BytesMessage) obj;

      if (type_ != other.type_) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BytesMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BytesMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BytesMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BytesMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BytesMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BytesMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BytesMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BytesMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static BytesMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static BytesMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BytesMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BytesMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BytesMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code remotecontrol.BytesMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:remotecontrol.BytesMessage)
        BytesMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BytesMessageProto.internal_static_remotecontrol_BytesMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BytesMessageProto.internal_static_remotecontrol_BytesMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BytesMessage.class, Builder.class);
      }

      // Construct using com.lkf.remotecontrol.models.BytesMessageProto.BytesMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = 0;
        data_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BytesMessageProto.internal_static_remotecontrol_BytesMessage_descriptor;
      }

      @Override
      public BytesMessage getDefaultInstanceForType() {
        return BytesMessage.getDefaultInstance();
      }

      @Override
      public BytesMessage build() {
        BytesMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public BytesMessage buildPartial() {
        BytesMessage result = new BytesMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(BytesMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.data_ = data_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BytesMessage) {
          return mergeFrom((BytesMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BytesMessage other) {
        if (other == BytesMessage.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                data_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.remotecontrol.Type type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.remotecontrol.Type type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.remotecontrol.Type type = 1;</code>
       * @return The type.
       */
      @Override
      public Type getType() {
        Type result = Type.forNumber(type_);
        return result == null ? Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.remotecontrol.Type type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.remotecontrol.Type type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 2;</code>
       * @return The data.
       */
      @Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:remotecontrol.BytesMessage)
    }

    // @@protoc_insertion_point(class_scope:remotecontrol.BytesMessage)
    private static final BytesMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BytesMessage();
    }

    public static BytesMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BytesMessage>
        PARSER = new com.google.protobuf.AbstractParser<BytesMessage>() {
      @Override
      public BytesMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BytesMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BytesMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public BytesMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VideoStreamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:remotecontrol.VideoStream)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 deviceId = 1;</code>
     * @return The deviceId.
     */
    long getDeviceId();

    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code remotecontrol.VideoStream}
   */
  public static final class VideoStream extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:remotecontrol.VideoStream)
      VideoStreamOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VideoStream.newBuilder() to construct.
    private VideoStream(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VideoStream() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new VideoStream();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BytesMessageProto.internal_static_remotecontrol_VideoStream_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BytesMessageProto.internal_static_remotecontrol_VideoStream_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VideoStream.class, Builder.class);
    }

    public static final int DEVICEID_FIELD_NUMBER = 1;
    private long deviceId_ = 0L;
    /**
     * <code>int64 deviceId = 1;</code>
     * @return The deviceId.
     */
    @Override
    public long getDeviceId() {
      return deviceId_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    @Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (deviceId_ != 0L) {
        output.writeInt64(1, deviceId_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (deviceId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, deviceId_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof VideoStream)) {
        return super.equals(obj);
      }
      VideoStream other = (VideoStream) obj;

      if (getDeviceId()
          != other.getDeviceId()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDeviceId());
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static VideoStream parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VideoStream parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VideoStream parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VideoStream parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VideoStream parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VideoStream parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VideoStream parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static VideoStream parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static VideoStream parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static VideoStream parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static VideoStream parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static VideoStream parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(VideoStream prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code remotecontrol.VideoStream}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:remotecontrol.VideoStream)
        VideoStreamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BytesMessageProto.internal_static_remotecontrol_VideoStream_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BytesMessageProto.internal_static_remotecontrol_VideoStream_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                VideoStream.class, Builder.class);
      }

      // Construct using com.lkf.remotecontrol.models.BytesMessageProto.VideoStream.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        deviceId_ = 0L;
        data_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BytesMessageProto.internal_static_remotecontrol_VideoStream_descriptor;
      }

      @Override
      public VideoStream getDefaultInstanceForType() {
        return VideoStream.getDefaultInstance();
      }

      @Override
      public VideoStream build() {
        VideoStream result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public VideoStream buildPartial() {
        VideoStream result = new VideoStream(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(VideoStream result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.deviceId_ = deviceId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.data_ = data_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof VideoStream) {
          return mergeFrom((VideoStream)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(VideoStream other) {
        if (other == VideoStream.getDefaultInstance()) return this;
        if (other.getDeviceId() != 0L) {
          setDeviceId(other.getDeviceId());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                deviceId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                data_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long deviceId_ ;
      /**
       * <code>int64 deviceId = 1;</code>
       * @return The deviceId.
       */
      @Override
      public long getDeviceId() {
        return deviceId_;
      }
      /**
       * <code>int64 deviceId = 1;</code>
       * @param value The deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceId(long value) {

        deviceId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 deviceId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 2;</code>
       * @return The data.
       */
      @Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:remotecontrol.VideoStream)
    }

    // @@protoc_insertion_point(class_scope:remotecontrol.VideoStream)
    private static final VideoStream DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new VideoStream();
    }

    public static VideoStream getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VideoStream>
        PARSER = new com.google.protobuf.AbstractParser<VideoStream>() {
      @Override
      public VideoStream parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<VideoStream> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<VideoStream> getParserForType() {
      return PARSER;
    }

    @Override
    public VideoStream getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TouchInputsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:remotecontrol.TouchInputs)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 deviceId = 1;</code>
     * @return The deviceId.
     */
    long getDeviceId();

    /**
     * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
     */
    java.util.List<MotionEvent>
        getMotionEventsList();
    /**
     * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
     */
    MotionEvent getMotionEvents(int index);
    /**
     * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
     */
    int getMotionEventsCount();
    /**
     * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
     */
    java.util.List<? extends MotionEventOrBuilder>
        getMotionEventsOrBuilderList();
    /**
     * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
     */
    MotionEventOrBuilder getMotionEventsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code remotecontrol.TouchInputs}
   */
  public static final class TouchInputs extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:remotecontrol.TouchInputs)
      TouchInputsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TouchInputs.newBuilder() to construct.
    private TouchInputs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TouchInputs() {
      motionEvents_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new TouchInputs();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BytesMessageProto.internal_static_remotecontrol_TouchInputs_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BytesMessageProto.internal_static_remotecontrol_TouchInputs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TouchInputs.class, Builder.class);
    }

    public static final int DEVICEID_FIELD_NUMBER = 1;
    private long deviceId_ = 0L;
    /**
     * <code>int64 deviceId = 1;</code>
     * @return The deviceId.
     */
    @Override
    public long getDeviceId() {
      return deviceId_;
    }

    public static final int MOTIONEVENTS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<MotionEvent> motionEvents_;
    /**
     * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
     */
    @Override
    public java.util.List<MotionEvent> getMotionEventsList() {
      return motionEvents_;
    }
    /**
     * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
     */
    @Override
    public java.util.List<? extends MotionEventOrBuilder>
        getMotionEventsOrBuilderList() {
      return motionEvents_;
    }
    /**
     * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
     */
    @Override
    public int getMotionEventsCount() {
      return motionEvents_.size();
    }
    /**
     * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
     */
    @Override
    public MotionEvent getMotionEvents(int index) {
      return motionEvents_.get(index);
    }
    /**
     * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
     */
    @Override
    public MotionEventOrBuilder getMotionEventsOrBuilder(
        int index) {
      return motionEvents_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (deviceId_ != 0L) {
        output.writeInt64(1, deviceId_);
      }
      for (int i = 0; i < motionEvents_.size(); i++) {
        output.writeMessage(2, motionEvents_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (deviceId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, deviceId_);
      }
      for (int i = 0; i < motionEvents_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, motionEvents_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TouchInputs)) {
        return super.equals(obj);
      }
      TouchInputs other = (TouchInputs) obj;

      if (getDeviceId()
          != other.getDeviceId()) return false;
      if (!getMotionEventsList()
          .equals(other.getMotionEventsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDeviceId());
      if (getMotionEventsCount() > 0) {
        hash = (37 * hash) + MOTIONEVENTS_FIELD_NUMBER;
        hash = (53 * hash) + getMotionEventsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TouchInputs parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TouchInputs parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TouchInputs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TouchInputs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TouchInputs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TouchInputs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TouchInputs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TouchInputs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static TouchInputs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static TouchInputs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TouchInputs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TouchInputs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TouchInputs prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code remotecontrol.TouchInputs}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:remotecontrol.TouchInputs)
        TouchInputsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BytesMessageProto.internal_static_remotecontrol_TouchInputs_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BytesMessageProto.internal_static_remotecontrol_TouchInputs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TouchInputs.class, Builder.class);
      }

      // Construct using com.lkf.remotecontrol.models.BytesMessageProto.TouchInputs.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        deviceId_ = 0L;
        if (motionEventsBuilder_ == null) {
          motionEvents_ = java.util.Collections.emptyList();
        } else {
          motionEvents_ = null;
          motionEventsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BytesMessageProto.internal_static_remotecontrol_TouchInputs_descriptor;
      }

      @Override
      public TouchInputs getDefaultInstanceForType() {
        return TouchInputs.getDefaultInstance();
      }

      @Override
      public TouchInputs build() {
        TouchInputs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public TouchInputs buildPartial() {
        TouchInputs result = new TouchInputs(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(TouchInputs result) {
        if (motionEventsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            motionEvents_ = java.util.Collections.unmodifiableList(motionEvents_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.motionEvents_ = motionEvents_;
        } else {
          result.motionEvents_ = motionEventsBuilder_.build();
        }
      }

      private void buildPartial0(TouchInputs result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.deviceId_ = deviceId_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TouchInputs) {
          return mergeFrom((TouchInputs)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TouchInputs other) {
        if (other == TouchInputs.getDefaultInstance()) return this;
        if (other.getDeviceId() != 0L) {
          setDeviceId(other.getDeviceId());
        }
        if (motionEventsBuilder_ == null) {
          if (!other.motionEvents_.isEmpty()) {
            if (motionEvents_.isEmpty()) {
              motionEvents_ = other.motionEvents_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureMotionEventsIsMutable();
              motionEvents_.addAll(other.motionEvents_);
            }
            onChanged();
          }
        } else {
          if (!other.motionEvents_.isEmpty()) {
            if (motionEventsBuilder_.isEmpty()) {
              motionEventsBuilder_.dispose();
              motionEventsBuilder_ = null;
              motionEvents_ = other.motionEvents_;
              bitField0_ = (bitField0_ & ~0x00000002);
              motionEventsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMotionEventsFieldBuilder() : null;
            } else {
              motionEventsBuilder_.addAllMessages(other.motionEvents_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                deviceId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                MotionEvent m =
                    input.readMessage(
                        MotionEvent.parser(),
                        extensionRegistry);
                if (motionEventsBuilder_ == null) {
                  ensureMotionEventsIsMutable();
                  motionEvents_.add(m);
                } else {
                  motionEventsBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long deviceId_ ;
      /**
       * <code>int64 deviceId = 1;</code>
       * @return The deviceId.
       */
      @Override
      public long getDeviceId() {
        return deviceId_;
      }
      /**
       * <code>int64 deviceId = 1;</code>
       * @param value The deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceId(long value) {

        deviceId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 deviceId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<MotionEvent> motionEvents_ =
        java.util.Collections.emptyList();
      private void ensureMotionEventsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          motionEvents_ = new java.util.ArrayList<MotionEvent>(motionEvents_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          MotionEvent, MotionEvent.Builder, MotionEventOrBuilder> motionEventsBuilder_;

      /**
       * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
       */
      public java.util.List<MotionEvent> getMotionEventsList() {
        if (motionEventsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(motionEvents_);
        } else {
          return motionEventsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
       */
      public int getMotionEventsCount() {
        if (motionEventsBuilder_ == null) {
          return motionEvents_.size();
        } else {
          return motionEventsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
       */
      public MotionEvent getMotionEvents(int index) {
        if (motionEventsBuilder_ == null) {
          return motionEvents_.get(index);
        } else {
          return motionEventsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
       */
      public Builder setMotionEvents(
          int index, MotionEvent value) {
        if (motionEventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMotionEventsIsMutable();
          motionEvents_.set(index, value);
          onChanged();
        } else {
          motionEventsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
       */
      public Builder setMotionEvents(
          int index, MotionEvent.Builder builderForValue) {
        if (motionEventsBuilder_ == null) {
          ensureMotionEventsIsMutable();
          motionEvents_.set(index, builderForValue.build());
          onChanged();
        } else {
          motionEventsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
       */
      public Builder addMotionEvents(MotionEvent value) {
        if (motionEventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMotionEventsIsMutable();
          motionEvents_.add(value);
          onChanged();
        } else {
          motionEventsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
       */
      public Builder addMotionEvents(
          int index, MotionEvent value) {
        if (motionEventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMotionEventsIsMutable();
          motionEvents_.add(index, value);
          onChanged();
        } else {
          motionEventsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
       */
      public Builder addMotionEvents(
          MotionEvent.Builder builderForValue) {
        if (motionEventsBuilder_ == null) {
          ensureMotionEventsIsMutable();
          motionEvents_.add(builderForValue.build());
          onChanged();
        } else {
          motionEventsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
       */
      public Builder addMotionEvents(
          int index, MotionEvent.Builder builderForValue) {
        if (motionEventsBuilder_ == null) {
          ensureMotionEventsIsMutable();
          motionEvents_.add(index, builderForValue.build());
          onChanged();
        } else {
          motionEventsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
       */
      public Builder addAllMotionEvents(
          Iterable<? extends MotionEvent> values) {
        if (motionEventsBuilder_ == null) {
          ensureMotionEventsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, motionEvents_);
          onChanged();
        } else {
          motionEventsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
       */
      public Builder clearMotionEvents() {
        if (motionEventsBuilder_ == null) {
          motionEvents_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          motionEventsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
       */
      public Builder removeMotionEvents(int index) {
        if (motionEventsBuilder_ == null) {
          ensureMotionEventsIsMutable();
          motionEvents_.remove(index);
          onChanged();
        } else {
          motionEventsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
       */
      public MotionEvent.Builder getMotionEventsBuilder(
          int index) {
        return getMotionEventsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
       */
      public MotionEventOrBuilder getMotionEventsOrBuilder(
          int index) {
        if (motionEventsBuilder_ == null) {
          return motionEvents_.get(index);  } else {
          return motionEventsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
       */
      public java.util.List<? extends MotionEventOrBuilder>
           getMotionEventsOrBuilderList() {
        if (motionEventsBuilder_ != null) {
          return motionEventsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(motionEvents_);
        }
      }
      /**
       * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
       */
      public MotionEvent.Builder addMotionEventsBuilder() {
        return getMotionEventsFieldBuilder().addBuilder(
            MotionEvent.getDefaultInstance());
      }
      /**
       * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
       */
      public MotionEvent.Builder addMotionEventsBuilder(
          int index) {
        return getMotionEventsFieldBuilder().addBuilder(
            index, MotionEvent.getDefaultInstance());
      }
      /**
       * <code>repeated .remotecontrol.MotionEvent motionEvents = 2;</code>
       */
      public java.util.List<MotionEvent.Builder>
           getMotionEventsBuilderList() {
        return getMotionEventsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          MotionEvent, MotionEvent.Builder, MotionEventOrBuilder>
          getMotionEventsFieldBuilder() {
        if (motionEventsBuilder_ == null) {
          motionEventsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              MotionEvent, MotionEvent.Builder, MotionEventOrBuilder>(
                  motionEvents_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          motionEvents_ = null;
        }
        return motionEventsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:remotecontrol.TouchInputs)
    }

    // @@protoc_insertion_point(class_scope:remotecontrol.TouchInputs)
    private static final TouchInputs DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TouchInputs();
    }

    public static TouchInputs getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TouchInputs>
        PARSER = new com.google.protobuf.AbstractParser<TouchInputs>() {
      @Override
      public TouchInputs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TouchInputs> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TouchInputs> getParserForType() {
      return PARSER;
    }

    @Override
    public TouchInputs getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MotionEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:remotecontrol.MotionEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float xAxis = 1;</code>
     * @return The xAxis.
     */
    float getXAxis();

    /**
     * <code>float yAxis = 2;</code>
     * @return The yAxis.
     */
    float getYAxis();

    /**
     * <code>int32 action = 3;</code>
     * @return The action.
     */
    int getAction();
  }
  /**
   * Protobuf type {@code remotecontrol.MotionEvent}
   */
  public static final class MotionEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:remotecontrol.MotionEvent)
      MotionEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MotionEvent.newBuilder() to construct.
    private MotionEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MotionEvent() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new MotionEvent();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BytesMessageProto.internal_static_remotecontrol_MotionEvent_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BytesMessageProto.internal_static_remotecontrol_MotionEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MotionEvent.class, Builder.class);
    }

    public static final int XAXIS_FIELD_NUMBER = 1;
    private float xAxis_ = 0F;
    /**
     * <code>float xAxis = 1;</code>
     * @return The xAxis.
     */
    @Override
    public float getXAxis() {
      return xAxis_;
    }

    public static final int YAXIS_FIELD_NUMBER = 2;
    private float yAxis_ = 0F;
    /**
     * <code>float yAxis = 2;</code>
     * @return The yAxis.
     */
    @Override
    public float getYAxis() {
      return yAxis_;
    }

    public static final int ACTION_FIELD_NUMBER = 3;
    private int action_ = 0;
    /**
     * <code>int32 action = 3;</code>
     * @return The action.
     */
    @Override
    public int getAction() {
      return action_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (Float.floatToRawIntBits(xAxis_) != 0) {
        output.writeFloat(1, xAxis_);
      }
      if (Float.floatToRawIntBits(yAxis_) != 0) {
        output.writeFloat(2, yAxis_);
      }
      if (action_ != 0) {
        output.writeInt32(3, action_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (Float.floatToRawIntBits(xAxis_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, xAxis_);
      }
      if (Float.floatToRawIntBits(yAxis_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, yAxis_);
      }
      if (action_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, action_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MotionEvent)) {
        return super.equals(obj);
      }
      MotionEvent other = (MotionEvent) obj;

      if (Float.floatToIntBits(getXAxis())
          != Float.floatToIntBits(
              other.getXAxis())) return false;
      if (Float.floatToIntBits(getYAxis())
          != Float.floatToIntBits(
              other.getYAxis())) return false;
      if (getAction()
          != other.getAction()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + XAXIS_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getXAxis());
      hash = (37 * hash) + YAXIS_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getYAxis());
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MotionEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MotionEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MotionEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MotionEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MotionEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MotionEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MotionEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MotionEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static MotionEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static MotionEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MotionEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MotionEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MotionEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code remotecontrol.MotionEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:remotecontrol.MotionEvent)
        MotionEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BytesMessageProto.internal_static_remotecontrol_MotionEvent_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BytesMessageProto.internal_static_remotecontrol_MotionEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MotionEvent.class, Builder.class);
      }

      // Construct using com.lkf.remotecontrol.models.BytesMessageProto.MotionEvent.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        xAxis_ = 0F;
        yAxis_ = 0F;
        action_ = 0;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BytesMessageProto.internal_static_remotecontrol_MotionEvent_descriptor;
      }

      @Override
      public MotionEvent getDefaultInstanceForType() {
        return MotionEvent.getDefaultInstance();
      }

      @Override
      public MotionEvent build() {
        MotionEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MotionEvent buildPartial() {
        MotionEvent result = new MotionEvent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(MotionEvent result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.xAxis_ = xAxis_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.yAxis_ = yAxis_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.action_ = action_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MotionEvent) {
          return mergeFrom((MotionEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MotionEvent other) {
        if (other == MotionEvent.getDefaultInstance()) return this;
        if (other.getXAxis() != 0F) {
          setXAxis(other.getXAxis());
        }
        if (other.getYAxis() != 0F) {
          setYAxis(other.getYAxis());
        }
        if (other.getAction() != 0) {
          setAction(other.getAction());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                xAxis_ = input.readFloat();
                bitField0_ |= 0x00000001;
                break;
              } // case 13
              case 21: {
                yAxis_ = input.readFloat();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              case 24: {
                action_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private float xAxis_ ;
      /**
       * <code>float xAxis = 1;</code>
       * @return The xAxis.
       */
      @Override
      public float getXAxis() {
        return xAxis_;
      }
      /**
       * <code>float xAxis = 1;</code>
       * @param value The xAxis to set.
       * @return This builder for chaining.
       */
      public Builder setXAxis(float value) {

        xAxis_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>float xAxis = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearXAxis() {
        bitField0_ = (bitField0_ & ~0x00000001);
        xAxis_ = 0F;
        onChanged();
        return this;
      }

      private float yAxis_ ;
      /**
       * <code>float yAxis = 2;</code>
       * @return The yAxis.
       */
      @Override
      public float getYAxis() {
        return yAxis_;
      }
      /**
       * <code>float yAxis = 2;</code>
       * @param value The yAxis to set.
       * @return This builder for chaining.
       */
      public Builder setYAxis(float value) {

        yAxis_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>float yAxis = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearYAxis() {
        bitField0_ = (bitField0_ & ~0x00000002);
        yAxis_ = 0F;
        onChanged();
        return this;
      }

      private int action_ ;
      /**
       * <code>int32 action = 3;</code>
       * @return The action.
       */
      @Override
      public int getAction() {
        return action_;
      }
      /**
       * <code>int32 action = 3;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(int value) {

        action_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 action = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000004);
        action_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:remotecontrol.MotionEvent)
    }

    // @@protoc_insertion_point(class_scope:remotecontrol.MotionEvent)
    private static final MotionEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MotionEvent();
    }

    public static MotionEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MotionEvent>
        PARSER = new com.google.protobuf.AbstractParser<MotionEvent>() {
      @Override
      public MotionEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MotionEvent> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MotionEvent> getParserForType() {
      return PARSER;
    }

    @Override
    public MotionEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_remotecontrol_BytesMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_remotecontrol_BytesMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_remotecontrol_VideoStream_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_remotecontrol_VideoStream_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_remotecontrol_TouchInputs_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_remotecontrol_TouchInputs_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_remotecontrol_MotionEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_remotecontrol_MotionEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022BytesMessage.proto\022\rremotecontrol\"?\n\014B" +
      "ytesMessage\022!\n\004type\030\001 \001(\0162\023.remotecontro" +
      "l.Type\022\014\n\004data\030\002 \001(\014\"-\n\013VideoStream\022\020\n\010d" +
      "eviceId\030\001 \001(\003\022\014\n\004data\030\002 \001(\014\"Q\n\013TouchInpu" +
      "ts\022\020\n\010deviceId\030\001 \001(\003\0220\n\014motionEvents\030\002 \003" +
      "(\0132\032.remotecontrol.MotionEvent\";\n\013Motion" +
      "Event\022\r\n\005xAxis\030\001 \001(\002\022\r\n\005yAxis\030\002 \001(\002\022\016\n\006a" +
      "ction\030\003 \001(\005*)\n\004Type\022\020\n\014VIDEO_STREAM\020\000\022\017\n" +
      "\013TOUCH_INPUT\020\001B3\n\034com.lkf.remotecontrol." +
      "modelsB\021BytesMessageProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_remotecontrol_BytesMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_remotecontrol_BytesMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_remotecontrol_BytesMessage_descriptor,
        new String[] { "Type", "Data", });
    internal_static_remotecontrol_VideoStream_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_remotecontrol_VideoStream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_remotecontrol_VideoStream_descriptor,
        new String[] { "DeviceId", "Data", });
    internal_static_remotecontrol_TouchInputs_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_remotecontrol_TouchInputs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_remotecontrol_TouchInputs_descriptor,
        new String[] { "DeviceId", "MotionEvents", });
    internal_static_remotecontrol_MotionEvent_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_remotecontrol_MotionEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_remotecontrol_MotionEvent_descriptor,
        new String[] { "XAxis", "YAxis", "Action", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
